apiVersion: v1
kind: ServiceAccount
metadata:
  name: niphas-operator
  namespace: {{ include "niphas.namespace" . }}
  labels:
    {{- include "niphas.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
