apiVersion: v1
kind: ConfigMap
metadata:
  name: niphas-config
  namespace: {{ include "niphas.namespace" . }}
  labels:
    {{- include "niphas.labels" . | nindent 4 }}
data:
  config.yaml: |
    logLevel: {{ .Values.config.logLevel | quote }}
    binaryCaches:
      {{- range .Values.config.binaryCaches }}
      - url: {{ .url | quote }}
        {{- if .publicKey }}
        publicKey: {{ .publicKey | quote }}
        {{- end }}
      {{- end }}
    allowedFlakeOrigins:
      {{- range .Values.config.allowedFlakeOrigins }}
      - {{ . | quote }}
      {{- end }}
    evalWebhookUrl: {{ .Values.config.evalWebhookUrl | quote }}
    healthPort: {{ .Values.config.healthPort }}
    evalTimeout: {{ .Values.config.evalTimeout | quote }}
    cache:
      path: {{ .Values.config.cache.path | quote }}
      highWatermarkBytes: {{ .Values.config.cache.highWatermark | int64 }}
      lowWatermarkBytes: {{ .Values.config.cache.lowWatermark | int64 }}
      gcInterval: {{ .Values.config.cache.gcInterval | quote }}
