apiVersion: niphas.io/v1alpha1
kind: NiphasWorkload
metadata:
  name: test-app
  namespace: niphas-e2e
spec:
  flakeRef: github:fullzer4/niphas?dir=hack/test-app
  attribute: packages.x86_64-linux.default
  replicas: 1
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: "8080"
        protocol: TCP
  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 64Mi
