apiVersion: niphas.io/v1alpha1
kind: NiphasWorkload
metadata:
  name: test-darkhttpd
  namespace: niphas-e2e
spec:
  flakeRef: github:nixos/nixpkgs
  attribute: legacyPackages.x86_64-linux.darkhttpd
  args:
    - "/tmp"
    - "--port"
    - "8080"
  replicas: 1
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: "8080"
        protocol: TCP
  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
