[package]
name = "niphas-csi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]
testutils = []

[dependencies]
niphas-core.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
tokio.workspace = true
tokio-stream = { version = "0.1", features = ["net"] }
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
bytes.workspace = true
async-compression.workspace = true
libc = "0.2"
hostname = "0.4"
tikv-jemallocator = { workspace = true, optional = true }

[dev-dependencies]
niphas-core = { workspace = true, features = ["testutils"] }
niphas-csi = { path = ".", features = ["testutils"] }
tonic.workspace = true
tokio.workspace = true

[build-dependencies]
tonic-build.workspace = true
tonic-prost-build.workspace = true
