apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: niphas.io.csi
  labels:
    {{- include "niphas.labels" . | nindent 4 }}
    app.kubernetes.io/component: csi
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
