[package]
name = "niphas-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
niphas-core.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
tikv-jemallocator = { workspace = true, optional = true }
